services:
  db:
    image: postgres:15-alpine
    ports:
      - "54347:5432"
    environment:
      POSTGRES_DB: kvk-handelsregister-test
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: password
